# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: market

on:
  push:
    branches: [ master ]

jobs:  
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
  
    - name: Test
      run: ./gradlew test
      
  build-image:
    runs-on: ubuntu-latest
    name: build-image
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        env:
          PORT: ${{ secrets.APP_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker login docker.pkg.github.com -u ${{ secrets.GIT_USER }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/${{ secrets.GIT_USER }}/market/market:latest
