# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: market

on:
  push:
    branches: [ master ]

jobs:  
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
  
    - name: Test
      run: ./gradlew test
      
  build-image:
    runs-on: ubuntu-latest
    name: build-image
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PORT: ${{ secrets.APP_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        with:
          name: ${{ secrets.GIT_USER }}/market/market
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
          buildargs: PORT,DB_HOST,DB_NAME,DB_USER,DB_PASSWORD,JWT_EXPIRATION,JWT_KEY
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_PORT: ${{ secrets.APP_PORT }}
          PORT_EXPOSED: ${{ secrets.PORT_EXPOSED }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USER_HOST }}
          key: ${{ secrets.KEY_HOST }}
          port: ${{ secrets.PORT_HOST }}
          envs: GIT_USER,GITHUB_TOKEN,APP_PORT,PORT_EXPOSED
          script: whoami
